# Generated by Django 5.2.4 on 2025-09-14 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='active_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 14, 1, 54, 31, 888385, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
