# Generated by Django 5.2.4 on 2025-09-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon_active_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
