# Generated by Django 5.2.4 on 2025-09-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_coupon_updated_date_alter_coupon_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amount_to_use_coupon',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
