# Generated by Django 5.2.4 on 2025-09-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_coupon_required_amount_to_use_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='required_amount_to_use_coupon',
            new_name='discount_coupon_amount',
        ),
    ]
